### PR TITLE
[TransferEngine][feature] add the http metadata server.

### LINKED ISSUE #29: proposal: add a new "http" metadata protocol
Glad to see https://github.com/kvcache-ai/Mooncake/pull/21 start to support multiple metadata servers.

Now, only etcd and redis are supported. I'm here to proposal a new "http" metadata type, benifits:
1. http metadata server are easy to deploy and scale.
2. the http metadata server could expose more APIs for system operator know/manage the system better.

Design:
The http server provide three restful APIs:
1. GET $metadata_uri?key=$key
2. PUT $$metadata_uri?key=$key, with json body
3. DELETE $metadata_uri?key=$key

If this does make sense, I'd like to have a try, thanks.

### PR DESCRIPTION
**Pull request by doujiang24**
follow up https://github.com/kvcache-ai/Mooncake/pull/21, fix #29 

TODO: doc and example for http server, will be another PR after this one merged.

### CODE REVIEW

**Comment by alogfans** [comment]
It's better to add doc and example for http server in this PR, so user can immediately use http mode. BTW the current's modification looks good to me.

**Comment by stmatengss** [comment]
@doujiang24 Thank you for your contribution. We will test this PR in our environment.

**Comment by alogfans** [comment]
LGTM

**Comment by stmatengss** [comment]
LGTM

**Pull request merged**
